### ISSUE TITLE
Help a lost lamb

### ISSUE THREAD

**Issue by myna-me** [TuxInvader/focal-mainline-builder#10]
TuxInvader: first off, THANK YOU. I was able to upgrade again.

This request is for a little hand holding on understanding, so I am ok if you say no, close it and ban me. lol.
Even though it takes forever to compile, i have run tests for buildmeta yes and no, rename yes and no, and every possible combination. ...and I am not getting something obviously.

So I was expecting that one of these combinations to yield 3 header files, 2 modules and 2 image debs....but I am getting that and many others. I have already passed the flag --exclude=cloud-tools,udebs,tools  but still get the following additional ones.:

- linux-cloud-tools-common-*
- linux-cloud-tools-common-*
- linux-source-*
- linux-tools-common-*
- linux-tools-host-*
- linux-buildinfo-*

So, here are my questions:

- Can you confirm that buildmeta basically adds:
  - linux-generic-kernelmajorversion_kernelactualversion.gz and deb
  - same but for latency.
-  can you confirm that rename, adds the version with no dots after the kernelactualversion? i wasn't really sure.
-  is there anything i can add to --exclude, so that i just get the 7 debs that you find in the kernel mainline site, but also to speed the compile by not having to do any work on the items that are supposed to be excluded?

Thank you in advance, thanks for your patience, and thanks again for this work!!!!

**Comment by TuxInvader** [comment]
Hi Myna-me,

Those exclude options don't work so well. I change the flags in the Makefiles, but some of the tools get built regardless. I didn't spend a lot of time investigating why, but I don't think they add a lot of additional time when compared to the kernel build.

The meta package does what you describe, it'll build a package which has dependencies on the current point release of a specific kernel version. This is useful in a PPA because it means you get automatic upgrades between point releases. I'm thinking about adding another meta package like `linux-generic-latest` which tracks across kernel releases too

The rename option is to stop my kernels from interfering with any standard kernel packages, and allow me to keep a few different versions of the kernel in the same PPA.

WRT fixing the excludes: I'm not sure how to forcibly exclude those packages, I'll need to dig back through the build files, and see where the variables are being overridden. But to be honest, if they are being ignored then it could be for a good reason, and meddling could cause other problems, which is why I just left it.

Hope that helps :-)

**Comment by myna-me** [comment]
Yes, it does. Thank you. This confirmed that I am not totally crazy. I agree with you, if it is still building them somewhere, then it is better to just leave them.
Thank you again. I'll close this so others that may be feeling lost can see it. :)
