### ISSUE TITLE
problem trying compile an software

### ISSUE THREAD

**Issue by Augusto7743** [TuxInvader/focal-mainline-builder#29]
Hello.
Thanks for making kernel updates.

Please see the link
https://github.com/pkoutoupis/rapiddisk/issues/133

Not is possible compile
warning: the compiler differs from the one used to build the kernel

What is exactly the compiler name used in yout kernel ?

Thanks for reply.

**Comment by TuxInvader** [comment]
As I commented on the bug over on rapiddisk. The compiler isn't the problem, it's the same version as ships with focal. The issue is that the 8.2.0 release doesn't support 5.19 kernels. 

You should be able to build the DKMS module using the code from the master branch, but that code doesn't support 6.0 yet, so you'll have to stick with 5.19.x until they add support for 6.0.

Cheers

**Comment by Augusto7743** [comment]
Thanks for your reply.
Nvidia driver 470 both nvidia binary and metapackage from Ubuntu not install in 6.00 too.

Have an nice week.
